version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Portfolio
hooks:
  ApplicationStop:
    - location: deployment/app_stop.sh
      timeout: 300

  BeforeInstall:

  AfterInstall:

  ApplicationStart:
    - location: deployment/app_start.sh
      timeout: 500
