version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Portfolio
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/Portfolio/deployment
    owner: root
    mode: 777
hooks:
  ApplicationStop:
    - location: deployment/app_stop.sh
      timeout: 300
      runas: root

  BeforeInstall:

  AfterInstall:
    - location: deployment/app_install.sh
      timeout: 120
      runas: root

  ApplicationStart:
    - location: deployment/app_start.sh
      timeout: 120
      runas: root
