version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Portfolio
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/Portfolio
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStop:
    - location: deployment/app_stop.sh
      timeout: 300
      runas: ubuntu

  BeforeInstall:

  AfterInstall:

  ApplicationStart:
    - location: deployment/app_start.sh
      timeout: 500
      runas: ubuntu
